// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParkLotManagementAPI.EfCore;

#nullable disable

namespace ParkLotManagementAPI.Migrations
{
    [DbContext(typeof(EF_DataContext))]
    [Migration("20230810115642_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.DailyLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int?>("DailyLogsId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("checkIn")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("checkOut")
                        .HasColumnType("time without time zone");

                    b.Property<int>("code")
                        .HasColumnType("integer");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<int>("subscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogsId");

                    b.ToTable("dailylogs");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.ParkSpots", b =>
                {
                    b.Property<int>("ParkSpotsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("ParkSpotsid"));

                    b.Property<int?>("ParkSpotsid1")
                        .HasColumnType("integer");

                    b.Property<int>("freeSpots")
                        .HasColumnType("integer");

                    b.Property<int?>("reservedSpots")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int>("totalSpots")
                        .HasColumnType("integer");

                    b.HasKey("ParkSpotsid");

                    b.HasIndex("ParkSpotsid1");

                    b.ToTable("parkSpots");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.Subscribers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("id"));

                    b.Property<int?>("Subscribersid")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("birthday")
                        .HasColumnType("date");

                    b.Property<int>("cardNumberId")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("phoneNumber")
                        .HasColumnType("integer");

                    b.Property<string>("plateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Subscribersid");

                    b.ToTable("subscribers");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.Subscriptions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("id"));

                    b.Property<int?>("Subscriptionsid")
                        .HasColumnType("integer");

                    b.Property<int>("code")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("endDate")
                        .HasColumnType("date");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("startDate")
                        .HasColumnType("date");

                    b.Property<int>("subscriberId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Subscriptionsid");

                    b.ToTable("subscriptions");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.WeekdayPricePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int?>("WeekdayPricePlanId")
                        .HasColumnType("integer");

                    b.Property<int>("dailyPrice")
                        .HasColumnType("integer");

                    b.Property<int>("hourlyPrice")
                        .HasColumnType("integer");

                    b.Property<int>("minimumHours")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeekdayPricePlanId");

                    b.ToTable("weekdaypriceplan");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.WeekendPricePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int?>("WeekendPricePlanId")
                        .HasColumnType("integer");

                    b.Property<int>("dailyPrice")
                        .HasColumnType("integer");

                    b.Property<int>("hourlyPrice")
                        .HasColumnType("integer");

                    b.Property<int>("minimumHours")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeekendPricePlanId");

                    b.ToTable("weekendpriceplan");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.DailyLogs", b =>
                {
                    b.HasOne("ParkLotManagementAPI.EfCore.DailyLogs", null)
                        .WithMany("dailylogs")
                        .HasForeignKey("DailyLogsId");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.ParkSpots", b =>
                {
                    b.HasOne("ParkLotManagementAPI.EfCore.ParkSpots", null)
                        .WithMany("parkSpots")
                        .HasForeignKey("ParkSpotsid1");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.Subscribers", b =>
                {
                    b.HasOne("ParkLotManagementAPI.EfCore.Subscribers", null)
                        .WithMany("subscribers")
                        .HasForeignKey("Subscribersid");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.Subscriptions", b =>
                {
                    b.HasOne("ParkLotManagementAPI.EfCore.Subscriptions", null)
                        .WithMany("subscriptions")
                        .HasForeignKey("Subscriptionsid");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.WeekdayPricePlan", b =>
                {
                    b.HasOne("ParkLotManagementAPI.EfCore.WeekdayPricePlan", null)
                        .WithMany("weekdaypriceplans")
                        .HasForeignKey("WeekdayPricePlanId");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.WeekendPricePlan", b =>
                {
                    b.HasOne("ParkLotManagementAPI.EfCore.WeekendPricePlan", null)
                        .WithMany("weekendpriceplans")
                        .HasForeignKey("WeekendPricePlanId");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.DailyLogs", b =>
                {
                    b.Navigation("dailylogs");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.ParkSpots", b =>
                {
                    b.Navigation("parkSpots");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.Subscribers", b =>
                {
                    b.Navigation("subscribers");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.Subscriptions", b =>
                {
                    b.Navigation("subscriptions");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.WeekdayPricePlan", b =>
                {
                    b.Navigation("weekdaypriceplans");
                });

            modelBuilder.Entity("ParkLotManagementAPI.EfCore.WeekendPricePlan", b =>
                {
                    b.Navigation("weekendpriceplans");
                });
#pragma warning restore 612, 618
        }
    }
}
